homeassistant: true
permit_join: false
frontend:
  port: 8082
  host: 192.168.0.2
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
  user: mqtt_user
  password: mqtt_pass
serial:
  port: /dev/ttyZigbee
advanced:
  channel: 25
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0xa4c1386726d2fa70':
    friendly_name: llumsPorxo
  '0x00158d0006ebfcf8':
    friendly_name: menjadorTemp
  '0x00158d0006ed23e6':
    friendly_name: '0x00158d0006ed23e6'
  '0x00158d0006ebff9e':
    friendly_name: '0x00158d0006ebff9e'
  '0x00124b0026b7788e':
    friendly_name: '0x00124b0026b7788e'
  '0xa4c1387f5feb34e4':
    friendly_name: '0xa4c1387f5feb34e4'
  '0xa4c1386ead9a47d8':
    friendly_name: '0xa4c1386ead9a47d8'
  '0xa4c13832fb8a5c1e':
    friendly_name: '0xa4c13832fb8a5c1e'
  '0xa4c138ac0f2c92e0':
    friendly_name: '0xa4c138ac0f2c92e0'
